[package]
name = "zeroing-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
csv = "1.3.1"
nix = { version = "0.30.1", features = ["ioctl"] }
serde = { version = "1.0.219", features = ["derive"] }
